services:
  - type: web
    name: coingokko
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn coingokko.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
